name: hp_response
description: A Flutter application to send responses to Google Sheets.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 # For authentication with Google APIs
  shared_preferences: ^2.3.3  # For storing user preferences
  intl: ^0.20.1 # For date formatting
  
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
flutter:
  uses-material-design: true

  assets:
    - assets/HP_round_logo-min(1).png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/HP_round_logo-min(1).png"  # Path to your app icon